require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommitLogsController do
=begin
  # This should return the minimal set of attributes required to create a valid
  # CommitLog. As you add validations to CommitLog, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    bob = User.create(:name => 'Bob', :email => 'bob@gmail.com', :pass => "bob")
    ruby = Type.create(:name => 'Ruby')
    {:commit_at => Time.now, :user_id => bob.id,:type_id => ruby.id }
  end

  describe "GET index" do
    it "assigns all commit_logs as @commit_logs" do
      commit_log = CommitLog.create! valid_attributes
      get :index
      assigns(:commit_logs).should eq([commit_log])
    end
  end

  describe "GET show" do
    it "assigns the requested commit_log as @commit_log" do
      commit_log = CommitLog.create! valid_attributes
      get :show, :id => commit_log.id
      assigns(:commit_log).should eq(commit_log)
    end
  end

  describe "GET new" do
    it "assigns a new commit_log as @commit_log" do
      get :new
      assigns(:commit_log).should be_a_new(CommitLog)
    end
  end

  describe "GET edit" do
    it "assigns the requested commit_log as @commit_log" do
      commit_log = CommitLog.create! valid_attributes
      get :edit, :id => commit_log.id
      assigns(:commit_log).should eq(commit_log)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommitLog" do
        expect {
          post :create, :commit_log => valid_attributes
        }.to change(CommitLog, :count).by(1)
      end

      it "assigns a newly created commit_log as @commit_log" do
        post :create, :commit_log => valid_attributes
        assigns(:commit_log).should be_a(CommitLog)
        assigns(:commit_log).should be_persisted
      end

      it "redirects to the created commit_log" do
        post :create, :commit_log => valid_attributes
        response.should redirect_to(CommitLog.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved commit_log as @commit_log" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommitLog.any_instance.stub(:save).and_return(false)
        post :create, :commit_log => {}
        assigns(:commit_log).should be_a_new(CommitLog)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommitLog.any_instance.stub(:save).and_return(false)
        post :create, :commit_log => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested commit_log" do
        commit_log = CommitLog.create! valid_attributes
        # Assuming there are no other commit_logs in the database, this
        # specifies that the CommitLog created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommitLog.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => commit_log.id, :commit_log => {'these' => 'params'}
      end

      it "assigns the requested commit_log as @commit_log" do
        commit_log = CommitLog.create! valid_attributes
        put :update, :id => commit_log.id, :commit_log => valid_attributes
        assigns(:commit_log).should eq(commit_log)
      end

      it "redirects to the commit_log" do
        commit_log = CommitLog.create! valid_attributes
        put :update, :id => commit_log.id, :commit_log => valid_attributes
        response.should redirect_to(commit_log)
      end
    end

    describe "with invalid params" do
      it "assigns the commit_log as @commit_log" do
        commit_log = CommitLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommitLog.any_instance.stub(:save).and_return(false)
        put :update, :id => commit_log.id, :commit_log => {}
        assigns(:commit_log).should eq(commit_log)
      end

      it "re-renders the 'edit' template" do
        commit_log = CommitLog.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommitLog.any_instance.stub(:save).and_return(false)
        put :update, :id => commit_log.id, :commit_log => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested commit_log" do
      commit_log = CommitLog.create! valid_attributes
      expect {
        delete :destroy, :id => commit_log.id
      }.to change(CommitLog, :count).by(-1)
    end

    it "redirects to the commit_logs list" do
      commit_log = CommitLog.create! valid_attributes
      delete :destroy, :id => commit_log.id
      response.should redirect_to(commit_logs_url)
    end
  end
=end
end
